In [8]:
import numpy as np
a=np.array([1,1,4,4,5,1,5,8,58,])
a.dtype

dtype('int32')

In [10]:
import numpy as np
a=np.array([4,1,4,499,5,1,5,8,58,])
a.dtype

dtype('int32')

In [16]:
import numpy as np
a=np.array([41,1,4,4,5,1,5,8,58,],dtype=np.float32)
a.dtype
a

array([41.,  1.,  4.,  4.,  5.,  1.,  5.,  8., 58.], dtype=float32)

In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a.dtype
a.size

7

In [23]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a.dtype.name

'int32'

In [3]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [5]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])