In [9]:
import numpy as np
a = np.arange(1,20,2)   
print(a) 
a.shape
a.ndim
a.itemsize
a.size
a.dtype
a.nbytes

[ 1  3  5  7  9 11 13 15 17 19]


40

In [15]:
import numpy
a=numpy.array([1,2,6,8,9])
b=numpy.array([8,7,9,5,6])
c=a+b
type(c)
type("numpy.ndarray")
c.shape

(5,)

In [26]:
import numpy as np
l=[[1,5,6,2],[8,5,6,2],[5,8,15,9]]
a=np.array(l)
print(a)
a.shape

[[ 1  5  6  2]
 [ 8  5  6  2]
 [ 5  8 15  9]]


(3, 4)

In [35]:
import numpy as np
M=np.array(([2,5,6],[3,4,9],[9,8,1]),dtype=complex)
M

array([[2.+0.j, 5.+0.j, 6.+0.j],
       [3.+0.j, 4.+0.j, 9.+0.j],
       [9.+0.j, 8.+0.j, 1.+0.j]])

In [38]:
import numpy
a=np.array([1,2,6,8,9])
b=np.array([8,7,9,5,6])
a+b


array([ 9,  9, 15, 13, 15])

In [46]:
print(a*b)
print(a%b)
print(a/b)
print(a**b)
a**a


[ 8 14 54 40 54]
[1 2 6 3 3]
[0.125      0.28571429 0.66666667 1.6        1.5       ]
[       1      128 10077696    32768   531441]


array([        1,         4,     46656,  16777216, 387420489], dtype=int32)

In [55]:
v=np.add(a,b)
v

array([ 9,  9, 15, 13, 15])

In [58]:
np.add(a,b,a) 
a

array([17, 16, 24, 18, 21])

In [59]:
np.array_equal(a,b)

False

In [6]:
import numpy as np
a=np.array([1,2,6,8,9],dtype=np.float64)
print(a.reshape(1,-1))
print(a.ravel())

[[1. 2. 6. 8. 9.]]
[1. 2. 6. 8. 9.]


In [11]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
x = a.ravel()

In [13]:
# import numpy as np
# a=np.array([1, 2, 3, 4, 5, 6])
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
import numpy as np
a=np.arange(12)
print(a)
b=a
b is a
b.shape=3,4
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(3, 4)

In [20]:
b=np.array([[1,4,5,8,6],[9,8,7,5,3]])

b=np.sort(b,axis=0)

b

array([[1, 4, 5, 5, 3],
       [9, 8, 7, 8, 6]])

In [26]:
import numpy as np
x = np.array([11,22])
y = np.array([18,7,6]) 
z = np.array([1,3,5]) 
c = np.concatenate((x,y,z))
print(c)
c=np.sort(c)
c

[11 22 18  7  6  1  3  5]


array([ 1,  3,  5,  6,  7, 11, 18, 22])

In [35]:
a = np.arange(5)
print(a)
np.sin(a) 
# np.log(a) 
# np.exp(a) 
# np.cos(a)

[0 1 2 3 4]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
import numpy as np
a=np.random.random((2,2))
b=np.random.random((2,2))
print(a,b)
p=np.vstack((a,b))
z=np.stack((a,b))
print(p)

print(z)

[[0.96117231 0.99006811]
 [0.60742257 0.41872345]] [[0.56146546 0.86628286]
 [0.4827257  0.95356341]]
[[0.96117231 0.99006811]
 [0.60742257 0.41872345]
 [0.56146546 0.86628286]
 [0.4827257  0.95356341]]
[[[0.96117231 0.99006811]
  [0.60742257 0.41872345]]

 [[0.56146546 0.86628286]
  [0.4827257  0.95356341]]]


In [100]:
import numpy as np
a=np.random.random((10,10))
print(a)
print(a.max())
print(a.min())
      


[[0.93115267 0.72037517 0.78235441 0.20082485 0.81427278 0.02813114
  0.21484166 0.88767079 0.49354578 0.54305715]
 [0.05638062 0.44495362 0.74863044 0.48846591 0.08173288 0.76989293
  0.69643901 0.05861852 0.58787579 0.65025029]
 [0.14934065 0.97979989 0.36765447 0.34020506 0.75953043 0.21412193
  0.32678866 0.59505801 0.15833274 0.95327452]
 [0.19673059 0.19032813 0.55925774 0.40059718 0.13914887 0.03054057
  0.00797158 0.68388129 0.8232049  0.23016199]
 [0.80018406 0.11123417 0.66469104 0.84878723 0.26856191 0.03827525
  0.7206302  0.06530505 0.43952031 0.262395  ]
 [0.88565067 0.52294014 0.42207717 0.67817114 0.31939505 0.44689757
  0.14049522 0.46382235 0.65895819 0.41583185]
 [0.19361872 0.25217783 0.51819114 0.88181159 0.37375602 0.9744204
  0.10247959 0.66763069 0.82895873 0.74772901]
 [0.23596655 0.75703552 0.57079844 0.87257678 0.77318945 0.07514357
  0.92329631 0.98706254 0.86686182 0.83296776]
 [0.74347519 0.6464151  0.51568539 0.22616109 0.9110265  0.35173348
  0.22026637 

0.00797158369908213

In [119]:
import numpy as np
a=np.ones((5,5))
print(a)
a[1:-1,1:-1] = 0
a

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [131]:
import numpy as np
x = np.arange(10)
print(x)
x = x[::-1]
print(x)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [130]:
a = np.arange(9).reshape(3,3)
np.flipud(a)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])